# Generated by Django 4.1.7 on 2023-04-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nerecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ne_type', models.CharField(max_length=50)),
                ('ne_name', models.CharField(max_length=50)),
                ('ne_ip', models.CharField(max_length=15)),
                ('aggreate_pe', models.CharField(max_length=50)),
                ('carrier_vlan_internet', models.IntegerField()),
                ('carrier_vlan_mpls', models.IntegerField()),
                ('pe_interface', models.CharField(max_length=20)),
                ('device_interfaces', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PErecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pe_model', models.CharField(max_length=40)),
                ('pe_name', models.CharField(max_length=50)),
                ('pe_ip1', models.CharField(max_length=15)),
                ('pe_ip2', models.CharField(max_length=15)),
                ('pe_interface1', models.CharField(max_length=20)),
                ('pe_interface2', models.CharField(max_length=20)),
                ('pe_interface3', models.CharField(max_length=20)),
                ('pe_interface4', models.CharField(max_length=20)),
            ],
        ),
    ]
