# Generated by Django 4.1.7 on 2023-04-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0002_alter_nerecords_carrier_vlan_mpls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerecords',
            name='carrier_vlan_mpls',
            field=models.IntegerField(),
        ),
    ]
