# Generated by Django 4.1.7 on 2023-04-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0005_alter_perecords_pe_interface1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerecords',
            name='pe_interface',
            field=models.CharField(max_length=50),
        ),
    ]
